### PR TITLE
Inference api

### LINKED ISSUE #5: Improve Model Analysis - Verbosity
As of now the models only display a positivity scale out of 100 or performs classification. Improve Tools to provide suggestions on improvement and provide autowriting tools for enhanced text.

### LINKED ISSUE #6: Improve Model Analysis - Classification of Speech
Classify and display components for better visual structurization of the data: Extraction of nouns, verbs etc. and highlights towards the same.

### PR DESCRIPTION
**Pull request by Vamsi995**
# Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #6 

# Type of Change:
**Delete irrelevant options.**

- Code

# How to run
Install the requirements

SpaCy:
pip install -U pip setuptools wheel
pip install -U spacy
python -m spacy download en_core_web_sm
pip install spacy-streamlit

1, cd streamlit
2. streamlit run sentiment.py
3. cd ../server
4. python3 server.py
5. Type the text in the text box and run.

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
It has been tested locally on my computer on streamlit.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by khanfarhan10 — APPROVED** [review]

**Comment by khanfarhan10** [comment]
Documentation in README needed, Rest is Great!

**Comment by khanfarhan10** [comment]
@Vamsi995 ? Documentation in README??

**Comment by Vamsi995** [comment]
I'm making the full application, so will put it after that.

**Comment by khanfarhan10** [comment]
Okay so will you make changes to this PR? Or create a new one??

**Comment by Vamsi995** [comment]
I will make changes to this pr itself

**Comment by khanfarhan10** [comment]
Put proper instructions in the documentation.

**Comment by khanfarhan10** [comment]
@Vamsi995 Today is the final date for submitting PRs. So please create the documentation changes really quickly.

**Comment by Vamsi995** [comment]
Done with the readme.

**Comment by khanfarhan10** [comment]
Great Job.

**Pull request merged**
