### PR TITLE
Adding model parameters

### LINKED ISSUE #3: Improve, Design & Optimize the NLP Models
The Models using BERT, LSTMs etc while improving and enhancing metrics should also be kept light-weight so as to be smooth for deployment purposes. If needed, reduce weight sizes using suitable conversions. (float64 to float16 etc.) Use [caching](https://docs.streamlit.io/en/stable/caching.html) wherever possible.

### PR DESCRIPTION
**Pull request by Vamsi995**
# Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #3

# Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Has been tested on colab for different examples.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by khanfarhan10 — CHANGES_REQUESTED** [review]
Could not understand what this PR does : the configuration file does exactly what? :(

You need to document the changes such that a layman can understand what this PR is all about!

**Comment by Vamsi995** [comment]
This pr includes the model configuration. I haven't uploaded the weights files because it exceeds 100MB. This file along with the weight file is used to instantiate the model.

**Comment by khanfarhan10** [comment]
Oh Okay. Try using GIT - Large File System (LFS) or try reducing weights by float64 to float8 conversions??
I can help on that subject matter. Exactly how large are the weights???

**Comment by Vamsi995** [comment]
the weights are 232MB. I tried using Git LFS but the problem was apparently you cant use it on forked repositories. You must own it to use git lfs.

**Comment by khanfarhan10** [comment]
Try using [this file](https://colab.research.google.com/drive/1fupkuMpsVTK-Y8TH4OWpBtiP2csmsghn?authuser=4#scrollTo=ByDSqYT9HkUh) or look at how to reduce h5/hdf5 dictionary weights from float64 to float16 and hopefully you can reduce the weights to around 60MB according to my estimates. If you face any problems, feel free to contact me!

**Comment by Vamsi995** [comment]
Hey im not able to access the file.

**Comment by khanfarhan10** [comment]
Try this link : https://colab.research.google.com/drive/1fupkuMpsVTK-Y8TH4OWpBtiP2csmsghn?usp=sharing

**Comment by Vamsi995** [comment]
hey farhan i have a pytorch model not a tensorflow one. Will this still work?

**Comment by Vamsi995** [comment]
Sry closed it by mistake !!

**Comment by khanfarhan10** [comment]
Not quite sure on how to implement the weight reduction analogy from tf to torch, but I'm sure there is a way out. A model so heavyweight will be impracticable to use in real time, hence I hope you understand the crticality of this step in model optimization.

**Comment by khanfarhan10** [comment]
Updates?

**Comment by khanfarhan10** [comment]
Were you able to transfer the model from torch to tf? @Vamsi995

**Comment by Vamsi995** [comment]
I wasn't able to make the transfer. I am thinking of using other models from spacy

**Comment by khanfarhan10** [comment]
Okay , Add instructions for running the Model Locally using pytorch.

Update requirements and add necessary commands/files. I will push the Weights myself if required (GIT LFS).

In the meantime, try to use spacy too to optimize the weight btw.

**Comment by Vamsi995** [comment]
Alright will add it to the readme by the end of the day.

**Comment by Vamsi995** [comment]
Also i will give you access to the weight files through drive.

**Comment by khanfarhan10** [comment]
Sure, Just notify me of any changes.

**Comment by Vamsi995** [comment]
https://drive.google.com/drive/folders/1-3wa1gCwLvxjcIEmU_MAjrQ-wA_515JR?usp=sharing

Here are the weight files in pytorch.

**Comment by khanfarhan10** [comment]
> https://drive.google.com/drive/folders/1-3wa1gCwLvxjcIEmU_MAjrQ-wA_515JR?usp=sharing
> 
> Here are the weight files in pytorch.

I just enabled GIT LFS on this repo, you should try once more. If the error occurs again then I'll help you.

**Comment by Vamsi995** [comment]
still cant push because I have a forked repository.

**Comment by khanfarhan10** [comment]
Okay then, approving changes. Will discuss with the mentor and push.

**Review by khanfarhan10 — APPROVED** [review]

**Pull request merged**
