### PR TITLE
Speech to text

### LINKED ISSUE #11: Voice Input
Voice Input of the sentences.
Converting user audio to text and using it as input.

### PR DESCRIPTION
**Pull request by Vamsi995**
# Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes #11  

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
I have tested this locally on my machine and this will work provided a frontend where this js file can be included.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by khanfarhan10 — CHANGES_REQUESTED** [review]
Create a documentation change in the README if required on how to operate using this changes when merged. Rest looks great and will immediately merge when you add the Instructions for Running! Good Job!

**Comment by Vamsi995** [comment]
For running this code we need a frontend where this script will be running. I can give a demo with a test HTML file, but once we have a legit frontend on flask we can just sideload this script into the main HTML file.

**Comment by khanfarhan10** [comment]
Hence, no documentation is required as of now?

**Comment by Vamsi995** [comment]
Yup not required now.

**Comment by khanfarhan10** [comment]
Merging this then!!!

**Pull request merged**
