### PR TITLE
Zip file upload

### LINKED ISSUE #4: Improve Utility Tools - Zip File Upload
Add a utility for uploading Zipfiles (containing various .txt files) and then run selected model over each files with verbose analytics.
Emails to senders.

### PR DESCRIPTION
**Pull request by Ankitasareen**
# Description
This PR is basically to add the feature of zip file upload, from which then csv files are extracted and predictions are made from the model. I have added one more feature, a link from where you can download the csv of the prediction dataframe generated.

Fixes #4 

# Type of Change:

- Code
- User Interface

#How to run
Install the requirements
Zipfile:
pip install zipfile36
pip install streamlit

1, cd streamlit
2. streamlit run app.py
3. Select the zip file and upload and then run.

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
It has been tested locally.

# Checklist:
**Delete irrelevant options.**

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [ ] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by khanfarhan10** [comment]
`pip install zipfile36`
Add this module to `requirements.txt` file with a suitable version and description as comment.
`PackageName==VersionName # VerboseComments`

**Comment by khanfarhan10** [comment]
Also don't create separate files for the same. Make and incorporate changes to a single app.py

**Comment by khanfarhan10** [comment]
@Ankitasareen ?

**Comment by Ankitasareen** [comment]
The change has been made to the readme and that for seperate files , once the pr is merged it will then be added from there to app.py because its being made by the other person.

**Pull request merged**
