### PR TITLE
Streamlit to flask connection

### LINKED ISSUE #13: Streamlit to flask connection
Sending API requests to flask server from streamlit

### PR DESCRIPTION
**Pull request by Vamsi995**
# Description
Setup to make streamlit to use the requests library to make API calls to flask backend server making it a frontend backend API setup.

Fixes #13 

# Type of Change:
**Delete irrelevant options.**

- Code

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
This has been tested on my local machine without any model inference.

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation
- [ ] I have made corresponding changes to the documentation
- [x] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Review by khanfarhan10 — CHANGES_REQUESTED** [review]
Same issue as the previous one , Lacks info on how to run the whole script, what it exactly performs : Create a documentation change in the README if required on how to operate using this changes when merged. Rest looks great and will immediately merge when you add the Instructions for Running! Good Job!

**Comment by Vamsi995** [comment]
Running the script :
1. Change to the directory of streamlit -> cd streamlit/
2. Start streamlit -> streamlit run sentiment.py
3. Change to the directory of server -> cd server/
4. Start flask server -> python3 server.py

In the streamlit localhost try typing the text into the textbox and hit analyze, the text you have written will be printed into the flask console.

**Comment by khanfarhan10** [comment]
Aha! Perhaps you might want to add Flask basic run instructions because the part to run it on Streamlit is already well defined??
Hence change the README a bit?

**Comment by Vamsi995** [comment]
Yeah i thought ill add the running instructions once I integrate the key word extraction part. Well this can be done later too I guess.

**Comment by khanfarhan10** [comment]
Sure, I'll merge this then. Be sure to add verbose documentations.

**Pull request merged**
