### PR TITLE
model report

### PR DESCRIPTION
**Pull request by Dineshkumar536**
# Description
Include a summary of the change and relevant motivation/context. List any dependencies that are required for this change.

Fixes # [ISSUE]

# Type of Change:
**Delete irrelevant options.**

- Code
- Quality Assurance
- User Interface
- Outreach
- Documentation

**Code/Quality Assurance Only**
- Bug fix (non-breaking change which fixes an issue)
- This change requires a documentation update (software upgrade on readme file)
- New feature (non-breaking change which adds functionality pre-approved by mentors)

# How Has This Been Tested?
Describe the tests you ran to verify your changes. Provide instructions or GIFs so we can reproduce. List any relevant details for your test.

# Checklist:
**Delete irrelevant options.**

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-review of my own code or materials
- [ ] I have commented my code or provided relevant documentation
- [ ] I have made corresponding changes to the documentation
- [ ] Any dependent changes have been merged 

**Code/Quality Assurance Only**
- [x] My changes generate no new warnings 
- [ ] My PR currently breaks something (fix or feature that would cause existing functionality to not work as expected)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been published in downstream modules

### CODE REVIEW

**Comment by khanfarhan10** [comment]
Please provide a proper description.
Next Time Keep seperate PRs for each task.

**Comment by khanfarhan10** [comment]
@Dineshkumar536 ???

**Comment by Dineshkumar536** [comment]
Yes

**Comment by khanfarhan10** [comment]
If you are still interested to keep this PR active :
- Please provide a proper description.
- Keep separate PRs for each task.

**Comment by Dineshkumar536** [comment]
Yes, I am working on it.

**Comment by Dineshkumar536** [comment]
Means i have to make different md files for every objective like , select
proper dataset as one md file and data preprocessing as another .

**Comment by khanfarhan10** [comment]
No @Dineshkumar536 , Like add PRs separately for Final Reports and App Deployment or Model Analysis. Are you getting it?

**Comment by Dineshkumar536** [comment]
No, I am not.

**Comment by khanfarhan10** [comment]
This PR contains :
- [Final Report](https://github.com/khanfarhan10/TextSentimentAnalysis/pull/26/files#diff-fbb0d47709cd55e56933579101ef05b44b9eb24d2b35c4d1c843d5d01e1077dc)
- [Sample (Example) Notebook](https://github.com/khanfarhan10/TextSentimentAnalysis/pull/26/files#diff-55ab93554f0ea068790729713198d641f3db0dd3e8f545c6cc4f426768573ee1)
- [Some Random Images](https://github.com/khanfarhan10/TextSentimentAnalysis/pull/26/files) - Scroll Down
- [Model Files](https://github.com/khanfarhan10/TextSentimentAnalysis/pull/26/files) (.pkl & others)
Please make individual Pull Requests for each of these.

P.S. - You might want to see the [Non-Inferable Description](https://github.com/khanfarhan10/TextSentimentAnalysis/pull/26) that you have provided for this Pull Request and consider revising it as a whole. Closing this PR and expecting individual PRs from you on each of the subject matters discussed above.

**Comment by Dineshkumar536** [comment]
Ya now understood

**Pull request closed without merging**
